Repository PennLINC/babs, pull requests merged in 2023-05, with the labels that each got.

#88 [ENH] Improve section names in container config YAML file
  babs/babs.py
  babs/cli.py
  babs/constants.py
  babs/utils.py
  docs/source/developer.rst
  docs/source/jobs.rst
  docs/source/preparation_config_yaml_file.rst
  notebooks/design_input_ds_argument.md
  notebooks/docs_developer.md
  notebooks/example_container_fmriprep.yaml
  notebooks/example_container_fmriprep_anatonly.yaml
  notebooks/example_container_fmriprep_ingressed_fs.yaml
  notebooks/example_container_fmriprep_sloppyFlag.yaml
  notebooks/example_container_fmriprepfake.yaml
  notebooks/example_container_qsiprep.yaml
  notebooks/example_container_toybidsapp.yaml
  notebooks/example_container_xcpd.yaml
  notebooks/example_container_zipped_toybidsapp.yaml
  notebooks/show_babs_init_InputBIDS.ipynb
  tests/test_babs_init.py
Labels: enhancement, breaking-changes

#90 [ENH] update toy BIDS App version used for CircleCI testing
  .circleci/config.yml
  .readthedocs.yaml
  .vscode/launch.json
  docs/source/babs-init.rst
  notebooks/example_container_toybidsapp.yaml
  notebooks/example_container_zipped_toybidsapp.yaml
  tests/get_data.py
Labels: documentation, enhancement, examples-enhancement

#92 [ENH] adding slurm as a system type
  babs/babs.py
  babs/dict_cluster_systems.yaml
  babs/utils.py
Labels: enhancement

#96 [ENH] test out BABS's Slurm version
  .vscode/launch.json
  babs/babs.py
  babs/utils.py
  notebooks/testing_babs_run.py
Labels: bug, enhancement

#98 [FIX/ENH] Fix directives and job accounting; enhance example container config YAML filenames
  .vscode/launch.json
  babs/babs.py
  babs/cli.py
  babs/dict_cluster_systems.yaml
  babs/utils.py
  docs/source/babs-status.rst
  docs/source/preparation_config_yaml_file.rst
  notebooks/README.md
  notebooks/docs_developer.md
  notebooks/eg_fmriprep-20-2-3_anatonly_sge_cubic.yaml
  notebooks/eg_fmriprep-20-2-3_full_sge_cubic.yaml
  notebooks/eg_fmriprep-20-2-3_ingressed-fs_sge_cubic.yaml
  notebooks/eg_fmriprep-20-2-3_sloppy_sge_cubic.yaml
  notebooks/eg_fmriprep-20-2-3_sloppy_slurm_msi.yaml
  notebooks/eg_fmriprepfake-0-1-1_full_sge_cubic.yaml
  notebooks/eg_qsiprep-0-16-0RC3_sloppy_sge_cubic.yaml
  notebooks/eg_qsiprep-0-16-0RC3_sloppy_slurm_msi.yaml
  notebooks/eg_toybidsapp-0-0-7_rawBIDS_sge_cubic.yaml
  notebooks/eg_toybidsapp-0-0-7_rawBIDS_slurm_msi.yaml
  notebooks/eg_toybidsapp-0-0-7_zipped_sge_cubic.yaml
  notebooks/eg_xcpd-0-3-0_full_sge_cubic.yaml
  notebooks/example_container_qsiprep.yaml
  notebooks/show_babs_init_InputBIDS.ipynb
  tests/get_data.py
  tests/test_babs_check_setup.py
  tests/test_babs_init.py
Labels: bug, documentation, enhancement
