Repository PennLINC/babs, pull requests merged in 2025-03, with the labels that each got.

#211 Replace `pkg_resources` with `importlib.metadata`
  babs/utils.py
  tox.ini
Labels: bug

#216 Fix RTD build
  .readthedocs.yaml
Labels: documentation

#210 Convert CLIs to subcommands
  .github/ISSUE_TEMPLATE/bug_report.md
  babs/babs.py
  babs/cli.py
  babs/template_test_job.py
  babs/utils.py
  docs/source/after_jobs.rst
  docs/source/babs-check-setup.rst
  docs/source/babs-init.rst
  docs/source/babs-merge.rst
  docs/source/babs-status.rst
  docs/source/babs-submit.rst
  docs/source/create_babs_project.rst
  docs/source/developer_babs_status.rst
  docs/source/developer_how_to_test.rst
  docs/source/jobs.rst
  docs/source/overview.rst
  docs/source/preparation_config_yaml_file.rst
  docs/source/preparation_container.rst
  docs/source/preparation_input_dataset.rst
  docs/source/walkthrough.rst
  docs/source/walkthrough_babs-check-setup_printed_messages.txt
  docs/source/walkthrough_babs-init_printed_messages.txt
  docs/source/walkthrough_babs-merge_printed_messages.txt
  notebooks/eg_fmriprep-20-2-3_ingressed-fs.yaml
  notebooks/eg_fmriprep-23-1-3_anatonly.yaml
  notebooks/eg_fmriprep-23-1-3_ingressed-fs.yaml
  pyproject.toml
  tests/e2e-slurm/container/walkthrough-tests.sh
  tests/test_babs_check_setup.py
  tests/test_babs_init.py
Labels: enhancement

#235 Convert `--project-root` to a positional argument
  babs/babs.py
  babs/cli.py
  babs/utils.py
  docs/after_jobs.rst
  docs/babs-check-setup.rst
  docs/babs-init.rst
  docs/babs-merge.rst
  docs/babs-status.rst
  docs/babs-submit.rst
  docs/developer_how_to_test.rst
  docs/jobs.rst
  docs/walkthrough.rst
  tests/e2e-slurm/container/walkthrough-tests.sh
  tests/test_babs_check_setup.py
  tests/test_babs_init.py
Labels: breaking-change

#243 Change `--container-config-yaml-file` to `--container-config`
  babs/babs.py
  babs/cli.py
  babs/utils.py
  docs/babs-init.rst
  docs/babs-status.rst
  docs/developer_babs_status.rst
  docs/developer_how_to_test.rst
  docs/jobs.rst
  docs/walkthrough.rst
  docs/walkthrough_babs-check-setup_printed_messages.txt
  docs/walkthrough_babs-init_printed_messages.txt
  tests/e2e-slurm/container/walkthrough-tests.sh
  tests/test_babs_check_setup.py
  tests/test_babs_init.py
Labels: breaking-change

#234 Change `--type-system` parameter to `--queue`
  babs/babs.py
  babs/cli.py
  babs/templates/babs_proj_config.yaml.jinja2
  babs/utils.py
  docs/babs-init.rst
  docs/walkthrough.rst
  docs/walkthrough_babs-check-setup_printed_messages.txt
  tests/e2e-slurm/container/walkthrough-tests.sh
  tests/get_data.py
  tests/someday_test_template_generation.py
  tests/test_babs_check_setup.py
  tests/test_babs_init.py
Labels: breaking-change

#251 Remove `--job-account` argument
  babs/babs.py
  babs/cli.py
  babs/utils.py
  docs/babs-status.rst
  docs/developer_babs_status.rst
  docs/developer_how_to_test.rst
  docs/jobs.rst
  docs/walkthrough.rst
Labels: breaking-change

#233 Change `--type-session` parameter to `--processing-level`
  .circleci/config.yml
  babs/babs.py
  babs/cli.py
  babs/templates/babs_proj_config.yaml.jinja2
  babs/templates/bidsapp_run.sh.jinja2
  babs/templates/datalad_run.sh.jinja2
  babs/templates/participant_job.sh.jinja2
  babs/utils.py
  docs/babs-init.rst
  docs/developer_babs_status.rst
  docs/developer_how_to_test.rst
  docs/walkthrough.rst
  docs/walkthrough_babs-check-setup_printed_messages.txt
  docs/walkthrough_babs-init_printed_messages.txt
  tests/e2e-slurm/container/walkthrough-tests.sh
  tests/get_data.py
  tests/origin_input_dataset.yaml
  tests/someday_test_template_generation.py
  tests/test_babs_check_setup.py
  tests/test_babs_init.py
Labels: breaking-change

#253 Remove commented-out code
  babs/babs.py
  babs/utils.py
Labels: refactor

#256 Make a separate system module
  babs/babs.py
  babs/cli.py
  babs/system.py
  babs/utils.py
  tests/someday_test_template_generation.py
  tests/test_system.py
Labels: refactor

#258 Move InputDatasets class into dataset module
  babs/babs.py
  babs/cli.py
  babs/dataset.py
  tests/someday_test_template_generation.py
Labels: refactor

#260 Remove unused functions and variables flagged by vulture
  babs/container.py
  babs/utils.py
Labels: refactor

#261 Add tests for function in utils module
  babs/babs.py
  babs/utils.py
  tests/test_utils.py
Labels: refactor

#270 Fix distribution on PyPi
  pyproject.toml
Labels: bug
